[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "cd apps/api/src && dotnet publish Msr.CommandCenter.Api/Msr.CommandCenter.Api/Msr.CommandCenter.Api.csproj -c Release -o out"
]

[start]
cmd = "cd apps/api/src && dotnet out/Msr.CommandCenter.Api.dll"
