[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "dotnet publish Msr.CommandCenter.Api/Msr.CommandCenter.Api/Msr.CommandCenter.Api.csproj -c Release -o out"
]

[start]
cmd = "dotnet out/Msr.CommandCenter.Api.dll"
