import type {
  ActivityEntry,
  AuditLogItem,
  BoardColumn,
  Card,
  CardComment,
  Invitation,
  NotificationItem,
  Organization,
  PersonalMsr,
  Project,
  ReportingCycle,
  ReportTemplate,
  Subtask,
  Team,
  TeamMsr,
  User,
} from "@/lib/types";
import { relativeDays } from "@/lib/utils";

export const demoNow = new Date("2026-04-01T12:00:00Z");

export const organization: Organization = {
  id: "org-northstar",
  name: "Northstar Operations",
  plan: "Enterprise",
  industry: "Professional Services",
  region: "North America",
  cadence: "monthly",
  branding: "Northstar blue",
};

export const users: User[] = [
  {
    id: "user-plat-admin",
    name: "Avery Chen",
    email: "avery@northstar.example",
    role: "PlatformAdmin",
    title: "Platform Administrator",
    teamIds: [],
    avatarColor: "#0f766e",
    status: "active",
  },
  {
    id: "user-org-admin",
    name: "Jordan Blake",
    email: "jordan@northstar.example",
    role: "OrgAdmin",
    title: "Director of Operations",
    teamIds: ["team-ops"],
    avatarColor: "#1d4ed8",
    status: "active",
  },
  {
    id: "user-manager-1",
    name: "Maya Patel",
    email: "maya@northstar.example",
    role: "Manager",
    title: "Delivery Manager",
    teamIds: ["team-delivery"],
    avatarColor: "#b45309",
    status: "active",
  },
  {
    id: "user-manager-2",
    name: "Ethan Morris",
    email: "ethan@northstar.example",
    role: "Manager",
    title: "Product Manager",
    teamIds: ["team-product"],
    avatarColor: "#be123c",
    status: "active",
  },
  { id: "user-1", name: "Sofia Reyes", email: "sofia@northstar.example", role: "TeamMember", title: "Senior Analyst", teamIds: ["team-delivery"], avatarColor: "#2563eb", status: "active", managerId: "user-manager-1" },
  { id: "user-2", name: "Miles Carter", email: "miles@northstar.example", role: "TeamMember", title: "Operations Associate", teamIds: ["team-delivery"], avatarColor: "#16a34a", status: "active", managerId: "user-manager-1" },
  { id: "user-3", name: "Nina Sharma", email: "nina@northstar.example", role: "TeamMember", title: "Implementation Lead", teamIds: ["team-delivery"], avatarColor: "#d97706", status: "active", managerId: "user-manager-1" },
  { id: "user-4", name: "Caleb Turner", email: "caleb@northstar.example", role: "TeamMember", title: "Product Designer", teamIds: ["team-product"], avatarColor: "#db2777", status: "active", managerId: "user-manager-2" },
  { id: "user-5", name: "Priya Singh", email: "priya@northstar.example", role: "TeamMember", title: "Product Analyst", teamIds: ["team-product"], avatarColor: "#7c3aed", status: "active", managerId: "user-manager-2" },
  { id: "user-6", name: "Leo Walker", email: "leo@northstar.example", role: "TeamMember", title: "QA Lead", teamIds: ["team-product"], avatarColor: "#0891b2", status: "active", managerId: "user-manager-2" },
  { id: "user-7", name: "Zoe Kim", email: "zoe@northstar.example", role: "TeamMember", title: "Finance Analyst", teamIds: ["team-ops"], avatarColor: "#ea580c", status: "active", managerId: "user-org-admin" },
  { id: "user-8", name: "Owen Brooks", email: "owen@northstar.example", role: "TeamMember", title: "People Ops Coordinator", teamIds: ["team-ops"], avatarColor: "#0d9488", status: "invited", managerId: "user-org-admin" },
  {
    id: "user-viewer",
    name: "Casey Grant",
    email: "casey@northstar.example",
    role: "ExecutiveViewer",
    title: "VP, Strategy",
    teamIds: [],
    avatarColor: "#475569",
    status: "active",
  },
];

export const teams: Team[] = [
  {
    id: "team-delivery",
    name: "Delivery",
    department: "Client Services",
    managerId: "user-manager-1",
    memberIds: ["user-1", "user-2", "user-3"],
    cadence: "monthly",
    health: "green",
    focus: "Client onboarding, delivery quality, and escalations",
  },
  {
    id: "team-product",
    name: "Product",
    department: "Product and Design",
    managerId: "user-manager-2",
    memberIds: ["user-4", "user-5", "user-6"],
    cadence: "biweekly",
    health: "amber",
    focus: "Launch readiness and experience improvements",
  },
  {
    id: "team-ops",
    name: "Operations",
    department: "Finance and People",
    managerId: "user-org-admin",
    memberIds: ["user-7", "user-8"],
    cadence: "monthly",
    health: "green",
    focus: "Operational reporting and hiring support",
  },
];

export const boardColumns: BoardColumn[] = [
  { id: "col-backlog", title: "Backlog", status: "Backlog", order: 0 },
  { id: "col-todo", title: "To Do", status: "To Do", order: 1 },
  { id: "col-progress", title: "In Progress", status: "In Progress", order: 2 },
  { id: "col-blocked", title: "Blocked", status: "Blocked", order: 3 },
  { id: "col-review", title: "Review", status: "Review", order: 4 },
  { id: "col-done", title: "Done", status: "Done", order: 5 },
];

export const projects: Project[] = [
  {
    id: "proj-1",
    name: "Q2 Customer Launch",
    status: "healthy",
    ownerId: "user-manager-1",
    teamIds: ["team-delivery", "team-product"],
    progress: 72,
    health: "Launch timeline is stable after scope reduction.",
    dueDate: relativeDays(demoNow, 18),
    summary: "Cross-functional launch with migration, training, and status reporting.",
  },
  {
    id: "proj-2",
    name: "Workflow Automation",
    status: "watch",
    ownerId: "user-manager-2",
    teamIds: ["team-product", "team-ops"],
    progress: 48,
    health: "Two approvals are waiting and one blocker is repeating across teams.",
    dueDate: relativeDays(demoNow, 10),
    summary: "Automation for recurring approvals and status updates.",
  },
  {
    id: "proj-3",
    name: "Finance Close Hardening",
    status: "healthy",
    ownerId: "user-org-admin",
    teamIds: ["team-ops"],
    progress: 85,
    health: "Controls are in place with a small follow-up queue.",
    dueDate: relativeDays(demoNow, 7),
    summary: "Close checklist, variance reporting, and ownership cleanup.",
  },
  {
    id: "proj-4",
    name: "Executive Reporting Pack",
    status: "at risk",
    ownerId: "user-viewer",
    teamIds: ["team-delivery", "team-product", "team-ops"],
    progress: 37,
    health: "Report inputs are inconsistent and require manager review.",
    dueDate: relativeDays(demoNow, 4),
    summary: "High-level weekly summary for leadership review.",
  },
];

export const cards: Card[] = [
  {
    id: "card-1",
    title: "Finalize onboarding playbook",
    description: "Update the launch checklist and confirm the manager sign-off path.",
    status: "In Progress",
    priority: "High",
    dueDate: relativeDays(demoNow, 2),
    projectId: "proj-1",
    ownerId: "user-1",
    assignedById: "user-manager-1",
    assignedAt: relativeDays(demoNow, -6),
    acknowledgedAt: relativeDays(demoNow, -6),
    collaboratorIds: ["user-4", "user-5"],
    tags: ["launch", "docs"],
    includeInMsr: true,
    ackRequired: true,
    visibility: "team",
    archived: false,
    updatedAt: relativeDays(demoNow, -1),
  },
  {
    id: "card-2",
    title: "Resolve billing mismatch",
    description: "Investigate the discrepancy and confirm with finance.",
    status: "Blocked",
    priority: "Critical",
    dueDate: relativeDays(demoNow, -1),
    projectId: "proj-3",
    ownerId: "user-7",
    assignedById: "user-org-admin",
    assignedAt: relativeDays(demoNow, -4),
    collaboratorIds: ["user-2"],
    tags: ["finance", "blocker"],
    includeInMsr: true,
    ackRequired: true,
    visibility: "manager",
    archived: false,
    blockedReason: "Waiting on vendor invoice correction.",
    updatedAt: relativeDays(demoNow, -1),
  },
  {
    id: "card-3",
    title: "Draft executive summary for launch",
    description: "Write the summary that rolls into the team MSR.",
    status: "Done",
    priority: "Medium",
    dueDate: relativeDays(demoNow, -3),
    projectId: "proj-4",
    ownerId: "user-5",
    assignedById: "user-manager-2",
    assignedAt: relativeDays(demoNow, -8),
    acknowledgedAt: relativeDays(demoNow, -8),
    collaboratorIds: ["user-4", "user-viewer"],
    tags: ["msr", "exec"],
    includeInMsr: true,
    ackRequired: false,
    visibility: "team",
    archived: false,
    updatedAt: relativeDays(demoNow, -2),
  },
  {
    id: "card-4",
    title: "QA regression sweep",
    description: "Run the smoke suite and capture defects before release.",
    status: "Review",
    priority: "High",
    dueDate: relativeDays(demoNow, 1),
    projectId: "proj-1",
    ownerId: "user-6",
    assignedById: "user-manager-2",
    assignedAt: relativeDays(demoNow, -5),
    acknowledgedAt: relativeDays(demoNow, -5),
    collaboratorIds: ["user-1"],
    tags: ["qa", "release"],
    includeInMsr: true,
    ackRequired: true,
    visibility: "team",
    archived: false,
    updatedAt: relativeDays(demoNow, -1),
  },
  {
    id: "card-5",
    title: "Workflow automation discovery",
    description: "Map the current manual steps and identify automation options.",
    status: "To Do",
    priority: "Medium",
    dueDate: relativeDays(demoNow, 8),
    projectId: "proj-2",
    ownerId: "user-4",
    assignedById: "user-manager-2",
    assignedAt: relativeDays(demoNow, -2),
    collaboratorIds: ["user-5"],
    tags: ["product", "process"],
    includeInMsr: true,
    ackRequired: true,
    visibility: "team",
    archived: false,
    updatedAt: relativeDays(demoNow, -2),
  },
  {
    id: "card-6",
    title: "Customer data cleanup",
    description: "Triage duplicates and reassign stale records.",
    status: "Backlog",
    priority: "Low",
    dueDate: relativeDays(demoNow, 12),
    projectId: "proj-2",
    ownerId: "user-2",
    assignedById: "user-manager-1",
    assignedAt: relativeDays(demoNow, -1),
    collaboratorIds: [],
    tags: ["ops"],
    includeInMsr: false,
    ackRequired: false,
    visibility: "private",
    archived: false,
    updatedAt: relativeDays(demoNow, -1),
  },
  {
    id: "card-7",
    title: "Publish monthly finance pack",
    description: "Assemble the final finance pack for leadership review.",
    status: "Done",
    priority: "High",
    dueDate: relativeDays(demoNow, -4),
    projectId: "proj-3",
    ownerId: "user-7",
    assignedById: "user-org-admin",
    assignedAt: relativeDays(demoNow, -10),
    acknowledgedAt: relativeDays(demoNow, -10),
    collaboratorIds: ["user-8"],
    tags: ["reporting"],
    includeInMsr: true,
    ackRequired: false,
    visibility: "team",
    archived: false,
    updatedAt: relativeDays(demoNow, -4),
  },
  {
    id: "card-8",
    title: "Leadership dashboard wireframe",
    description: "Create the dashboard concept for executive viewers.",
    status: "Blocked",
    priority: "High",
    dueDate: relativeDays(demoNow, 3),
    projectId: "proj-4",
    ownerId: "user-viewer",
    assignedById: "user-manager-2",
    assignedAt: relativeDays(demoNow, -3),
    collaboratorIds: ["user-1", "user-6"],
    tags: ["dashboard", "exec"],
    includeInMsr: true,
    ackRequired: true,
    visibility: "manager",
    archived: false,
    blockedReason: "Waiting for final branding assets.",
    updatedAt: relativeDays(demoNow, -1),
  },
  {
    id: "card-9",
    title: "Review launch blockers with Product",
    description: "Walk through the open blockers and decide on escalation paths.",
    status: "Review",
    priority: "High",
    dueDate: relativeDays(demoNow, 1),
    projectId: "proj-1",
    ownerId: "user-manager-1",
    assignedById: "user-org-admin",
    assignedAt: relativeDays(demoNow, -3),
    acknowledgedAt: relativeDays(demoNow, -3),
    collaboratorIds: ["user-4", "user-5", "user-6"],
    tags: ["manager", "review"],
    includeInMsr: true,
    ackRequired: true,
    visibility: "manager",
    archived: false,
    updatedAt: relativeDays(demoNow, -1),
  },
  {
    id: "card-10",
    title: "Prepare weekly team roundup",
    description: "Summarize progress, blockers, and follow-up items for the next manager sync.",
    status: "To Do",
    priority: "Medium",
    dueDate: relativeDays(demoNow, 4),
    projectId: "proj-4",
    ownerId: "user-manager-1",
    assignedById: "user-org-admin",
    assignedAt: relativeDays(demoNow, -1),
    collaboratorIds: ["user-1", "user-2"],
    tags: ["manager", "msr"],
    includeInMsr: true,
    ackRequired: false,
    visibility: "manager",
    archived: false,
    updatedAt: relativeDays(demoNow, -1),
  },
];

export const cardComments: CardComment[] = [
  { id: "comment-1", cardId: "card-1", authorId: "user-4", body: "Added the updated onboarding checklist and linked the launch notes.", createdAt: relativeDays(demoNow, -2) },
  { id: "comment-2", cardId: "card-2", authorId: "user-7", body: "Finance is waiting on the corrected invoice from the vendor.", createdAt: relativeDays(demoNow, -1) },
  { id: "comment-3", cardId: "card-8", authorId: "user-6", body: "Branding assets are the remaining dependency for the mockup.", createdAt: relativeDays(demoNow, -1) },
];

export const subtasks: Subtask[] = [
  { id: "subtask-1", cardId: "card-1", title: "Confirm launch checklist owner", assigneeId: "user-1", completed: true },
  { id: "subtask-2", cardId: "card-1", title: "Collect final manager feedback", assigneeId: "user-4", completed: false },
  { id: "subtask-3", cardId: "card-4", title: "Run smoke suite", assigneeId: "user-6", completed: true },
  { id: "subtask-4", cardId: "card-4", title: "Log regressions", assigneeId: "user-1", completed: false },
];

export const activityEntries: ActivityEntry[] = [
  {
    id: "act-1",
    userId: "user-1",
    cardId: "card-1",
    projectId: "proj-1",
    kind: "accomplishment",
    title: "Completed onboarding checklist edits",
    body: "Reworked the launch checklist and aligned with the product owner on sign-off.",
    createdAt: relativeDays(demoNow, -1),
  },
  {
    id: "act-2",
    userId: "user-7",
    cardId: "card-2",
    projectId: "proj-3",
    kind: "blocker",
    title: "Vendor invoice mismatch",
    body: "Still blocked on invoice correction before the finance pack can be finalized.",
    createdAt: relativeDays(demoNow, -1),
  },
  {
    id: "act-3",
    userId: "user-4",
    projectId: "proj-2",
    kind: "daily note",
    title: "Discovery notes captured",
    body: "Captured workflow discovery questions and clarified who owns automation review.",
    createdAt: relativeDays(demoNow, -2),
  },
  {
    id: "act-4",
    userId: "user-6",
    cardId: "card-4",
    projectId: "proj-1",
    kind: "card update",
    title: "QA sweep moved to review",
    body: "Finished the regression run and moved the task to review.",
    createdAt: relativeDays(demoNow, -1),
  },
  {
    id: "act-5",
    userId: "user-manager-1",
    projectId: "proj-1",
    kind: "next step",
    title: "Prepared manager review notes",
    body: "Queued the launch blocker follow-up and weekly roundup outline.",
    createdAt: relativeDays(demoNow, -1),
  },
];

export const reportingCycles: ReportingCycle[] = [
  {
    id: "cycle-delivery-mar",
    teamId: "team-delivery",
    cadence: "monthly",
    startDate: relativeDays(demoNow, -29),
    endDate: relativeDays(demoNow, -1),
    dueDate: relativeDays(demoNow, 1),
    submissionDeadline: relativeDays(demoNow, 2),
    status: "pending review",
  },
  {
    id: "cycle-product-mar",
    teamId: "team-product",
    cadence: "biweekly",
    startDate: relativeDays(demoNow, -13),
    endDate: relativeDays(demoNow, 1),
    dueDate: relativeDays(demoNow, 2),
    submissionDeadline: relativeDays(demoNow, 3),
    status: "open",
  },
  {
    id: "cycle-ops-mar",
    teamId: "team-ops",
    cadence: "monthly",
    startDate: relativeDays(demoNow, -29),
    endDate: relativeDays(demoNow, -1),
    dueDate: relativeDays(demoNow, 2),
    submissionDeadline: relativeDays(demoNow, 4),
    status: "finalized",
  },
];

export const personalMsrs: PersonalMsr[] = [
  {
    id: "msr-1",
    userId: "user-1",
    cycleId: "cycle-delivery-mar",
    status: "submitted",
    generated: [
      {
        title: "Accomplishments",
        body: "Delivered the onboarding checklist update, closed out launch prep tasks, and kept QA unblockers moving.",
        bullets: ["Completed the updated onboarding checklist.", "Worked with Product on sign-off details.", "Contributed to launch readiness and review notes."],
      },
      {
        title: "Current Work",
        body: "Finishing the launch playbook and coordinating review comments.",
        bullets: ["Launch playbook final edits.", "QA regression follow-up.", "Manager feedback consolidation."],
      },
      {
        title: "Blockers / Risks",
        body: "No major blockers, but the review queue is tight.",
        bullets: ["Waiting on one review response.", "Testing dependencies need final confirmation."],
      },
    ],
    edited: [
      {
        title: "Accomplishments",
        body: "Updated the onboarding checklist, aligned launch details with Product, and kept review items moving.",
        bullets: ["Completed the updated onboarding checklist.", "Partnered on launch readiness.", "Kept review work moving quickly."],
      },
      {
        title: "Current Work",
        body: "Finalizing the playbook and closing open review comments.",
        bullets: ["Launch playbook final edits.", "QA regression follow-up."],
      },
      {
        title: "Blockers / Risks",
        body: "Review timing is the main risk this cycle.",
        bullets: ["One pending response.", "Release timing is tight."],
      },
    ],
    final: [
      {
        title: "Accomplishments",
        body: "Updated the onboarding checklist, aligned launch details with Product, and kept review items moving.",
        bullets: ["Completed the updated onboarding checklist.", "Partnered on launch readiness.", "Kept review work moving quickly."],
      },
      {
        title: "Current Work",
        body: "Finalizing the playbook and closing open review comments.",
        bullets: ["Launch playbook final edits.", "QA regression follow-up."],
      },
      {
        title: "Blockers / Risks",
        body: "Review timing is the main risk this cycle.",
        bullets: ["One pending response.", "Release timing is tight."],
      },
    ],
    updatedAt: relativeDays(demoNow, -1),
    versionHistory: [
      { label: "Generated draft", author: "System", at: relativeDays(demoNow, -2) },
      { label: "User edits", author: "Sofia Reyes", at: relativeDays(demoNow, -1) },
      { label: "Submitted", author: "Sofia Reyes", at: relativeDays(demoNow, -1) },
    ],
  },
  {
    id: "msr-2",
    userId: "user-5",
    cycleId: "cycle-product-mar",
    status: "draft",
    generated: [
      {
        title: "Accomplishments",
        body: "Contributed to launch reporting and helped shape the executive summary.",
        bullets: ["Drafted the executive summary.", "Provided product context for leadership reporting."],
      },
      {
        title: "Upcoming Work",
        body: "Finish the launch narrative and align dependencies.",
        bullets: ["Finalize the reporting pack.", "Resolve cross-team dependencies."],
      },
    ],
    edited: [
      {
        title: "Accomplishments",
        body: "Contributed to launch reporting and drafted the executive summary.",
        bullets: ["Drafted the executive summary.", "Clarified leadership metrics."],
      },
      {
        title: "Upcoming Work",
        body: "Finish the launch narrative and align dependencies.",
        bullets: ["Finalize the reporting pack.", "Resolve dependencies."],
      },
    ],
    final: [
      {
        title: "Accomplishments",
        body: "Contributed to launch reporting and drafted the executive summary.",
        bullets: ["Drafted the executive summary.", "Clarified leadership metrics."],
      },
      {
        title: "Upcoming Work",
        body: "Finish the launch narrative and align dependencies.",
        bullets: ["Finalize the reporting pack.", "Resolve dependencies."],
      },
    ],
    updatedAt: relativeDays(demoNow, -2),
    versionHistory: [{ label: "Generated draft", author: "System", at: relativeDays(demoNow, -2) }],
  },
  {
    id: "msr-3",
    userId: "user-manager-1",
    cycleId: "cycle-delivery-mar",
    status: "draft",
    generated: [
      {
        title: "Accomplishments",
        body: "Kept delivery work moving, resolved blocker follow-ups, and reviewed launch readiness.",
        bullets: ["Reviewed open blockers with Product.", "Supported launch readiness."],
      },
      {
        title: "Current Work",
        body: "Preparing the weekly roundup and manager review notes.",
        bullets: ["Weekly roundup preparation.", "Blocker escalation review."],
      },
      {
        title: "Blockers / Risks",
        body: "Review turnaround from cross-functional partners remains the biggest risk.",
        bullets: ["Response lag on approvals.", "Launch timing depends on final decisions."],
      },
    ],
    edited: [
      {
        title: "Accomplishments",
        body: "Kept delivery work moving, resolved blocker follow-ups, and reviewed launch readiness.",
        bullets: ["Reviewed open blockers with Product.", "Supported launch readiness."],
      },
      {
        title: "Current Work",
        body: "Preparing the weekly roundup and manager review notes.",
        bullets: ["Weekly roundup preparation.", "Blocker escalation review."],
      },
      {
        title: "Blockers / Risks",
        body: "Review turnaround from cross-functional partners remains the biggest risk.",
        bullets: ["Response lag on approvals.", "Launch timing depends on final decisions."],
      },
    ],
    final: [
      {
        title: "Accomplishments",
        body: "Kept delivery work moving, resolved blocker follow-ups, and reviewed launch readiness.",
        bullets: ["Reviewed open blockers with Product.", "Supported launch readiness."],
      },
      {
        title: "Current Work",
        body: "Preparing the weekly roundup and manager review notes.",
        bullets: ["Weekly roundup preparation.", "Blocker escalation review."],
      },
      {
        title: "Blockers / Risks",
        body: "Review turnaround from cross-functional partners remains the biggest risk.",
        bullets: ["Response lag on approvals.", "Launch timing depends on final decisions."],
      },
    ],
    updatedAt: relativeDays(demoNow, -1),
    versionHistory: [{ label: "Generated draft", author: "System", at: relativeDays(demoNow, -1) }],
  },
];

export const teamMsrs: TeamMsr[] = [
  {
    id: "team-msr-1",
    teamId: "team-delivery",
    cycleId: "cycle-delivery-mar",
    status: "finalized",
    executiveSummary:
      "Delivery finished the onboarding refresh and kept launch work moving while reducing review lag. The main risk remains turnaround time on final approvals.",
    sections: [
      {
        title: "Executive Summary",
        body: "Delivery had a strong month with visible progress on onboarding and launch readiness.",
        bullets: ["Completed onboarding updates.", "Kept QA and launch work coordinated.", "Surface risks early to managers."],
      },
      {
        title: "Blockers / Risks",
        body: "No systemic issues, but review timing is tight for launch tasks.",
        bullets: ["Delayed responses on one review thread.", "Launch timing depends on final sign-off."],
      },
    ],
    appendix: [
      { userId: "user-1", highlights: ["Onboarding checklist edits", "QA review support"] },
      { userId: "user-2", highlights: ["Operational cleanup", "Billing mismatch follow-up"] },
      { userId: "user-3", highlights: ["Implementation planning", "Client readiness"] },
    ],
    updatedAt: relativeDays(demoNow, -1),
    versionHistory: [
      { label: "Compiled from personal MSRs", author: "System", at: relativeDays(demoNow, -1) },
      { label: "Manager edits", author: "Maya Patel", at: relativeDays(demoNow, -1) },
      { label: "Finalized", author: "Maya Patel", at: relativeDays(demoNow, -1) },
    ],
  },
];

export const notifications: NotificationItem[] = [
  {
    id: "notif-1",
    userId: "user-1",
    kind: "assignment",
    title: "New assignment from Maya Patel",
    body: "Finalize onboarding playbook is due in 2 days.",
    href: "/my-board",
    createdAt: relativeDays(demoNow, -1),
    read: false,
  },
  {
    id: "notif-2",
    userId: "user-7",
    kind: "reminder",
    title: "MSR submission due soon",
    body: "Your reporting cycle closes tomorrow.",
    href: "/personal-msr-editor",
    createdAt: relativeDays(demoNow, -1),
    read: false,
  },
  {
    id: "notif-3",
    userId: "user-manager-1",
    kind: "review",
    title: "3 personal MSRs ready for review",
    body: "Delivery cycle submissions are ready to compile.",
    href: "/team-msr-builder",
    createdAt: relativeDays(demoNow, -1),
    read: true,
  },
];

export const auditLogs: AuditLogItem[] = [
  { id: "audit-1", actorId: "user-manager-1", action: "Assigned card", target: "Finalize onboarding playbook", targetId: "card-1", details: "Assigned with acknowledgment required.", createdAt: relativeDays(demoNow, -6) },
  { id: "audit-2", actorId: "user-7", action: "Updated blocker", target: "Resolve billing mismatch", targetId: "card-2", details: "Added blocker note for vendor invoice correction.", createdAt: relativeDays(demoNow, -1) },
  { id: "audit-3", actorId: "user-manager-2", action: "Compiled team MSR", target: "Delivery cycle", targetId: "team-msr-1", details: "Compiled from submitted personal MSRs.", createdAt: relativeDays(demoNow, -1) },
];

export const templates: ReportTemplate[] = [
  {
    id: "template-default",
    name: "Standard Monthly MSR",
    cadence: "monthly",
    requiredSections: ["Accomplishments", "Current Work", "Blockers / Risks", "Upcoming Work"],
    questionPrompts: [
      "What did you finish this cycle?",
      "What is still in flight?",
      "What is blocking you?",
      "What should your manager know?",
    ],
    branding: "Northstar standard",
  },
  {
    id: "template-exec",
    name: "Executive Summary Pack",
    cadence: "monthly",
    requiredSections: ["Executive Summary", "Highlights", "Risks", "Next Steps"],
    questionPrompts: ["What changed this cycle?", "Where should leadership pay attention?"],
    branding: "Leadership branded",
  },
];

export const invitations: Invitation[] = [
  { id: "invite-1", email: "owen@northstar.example", role: "TeamMember", teamId: "team-ops", sentBy: "user-org-admin", status: "pending" },
  { id: "invite-2", email: "new-manager@northstar.example", role: "Manager", teamId: "team-product", sentBy: "user-org-admin", status: "accepted" },
];
